language: cpp
compiler: gcc

matrix:
  include:
    - os: linux
      sudo: true
      dist: xenial
      compiler: gcc
      addons:
        apt:
          sources: 
            - sourceline: 'ppa:mhier/libboost-latest'
            - sourceline: 'deb https://apt.repos.intel.com/mkl all main'
              key_url: https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - cmake
            - libboost1.68-dev
            - libhdf5-dev
            - intel-mkl-64bit-2019.1-053
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

    # - os: osx
    #   osx_image: xcode8
    #   env:
    #     - MATRIX_EVAL="brew install clang && CC=clang && CXX=clang++"

script:
  - mkdir build
  - cd build
  - eval "${MATRIX_EVAL}"
  - cmake -DENABLE_TESTING=1
          -DLAPACK_ROOT=/opt/intel/compilers_and_libraries_2019.1.144/linux/mkl
          -DLAPACK_LIBRARIES="libmkl_intel_ilp64.a libmkl_intel_thread.a libmkl_core.a"
          ..
  - make -j 2
  - make test

# Disable notifications
notifications:
  email: false