language: cpp
compiler: gcc

matrix:
  include:
    - os: linux
      sudo: true
      dist: xenial
      compiler: gcc
      addons:
        apt:
          sources: 
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-7 main'
            - key_url: https://apt.llvm.org/llvm-snapshot.gpg.key
            - sourceline: 'ppa:mhier/libboost-latest'
            # https://software.intel.com/en-us/articles/installing-intel-free-libs-and-python-apt-repo
            - sourceline: 'deb https://apt.repos.intel.com/mkl all main'
              key_url: https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - clang-7
            - cmake
            - ninja-build
            - intel-mkl-64bit-2019.2-057
      env:
        - MATRIX_EVAL="CC=clang-7 && CXX=clang++-7 LDFLAGS=-static-libgcc -static-libstdc++ MKLROOT=/opt/intel/compilers_and_libraries/linux/mkl"

    # - os: osx
    #   osx_image: xcode8
    #   env:
    #     - MATRIX_EVAL="brew install clang && CC=clang && CXX=clang++"

script:
  - git clone https://github.com/fradav/vcpkg.git
  - cd vcpkg
  - ./bootstrap-vcpkg -useSystemBinaries -disableMetrics
  - ./vcpkg integrate install
  - ./vcpkg install range-v3 eigen3 catch2 hdf5[cpp] highfive
  - cd ..
  - mkdir build
  - cd build
  - eval "${MATRIX_EVAL}"
  - cmake -G Ninja 
           -DCMAKE=../vcpkg/scripts/buildsystems/vcpkg.cmake
          -DLAPACK_ROOT=${MKLROOT}/lib/intel64
          -DLAPACK_LIBRARIES="-Wl,--start-group ${MKLROOT}/lib/intel64/libmkl_intel_lp64.a ${MKLROOT}/lib/intel64/libmkl_sequential.a ${MKLROOT}/lib/intel64/libmkl_core.a -Wl,--end-group;dl"
          -DCMAKE_BUILD_TYPE=Release
          -DRFTEST_TOLERANCE=2e-2
          ..
  - ninja
  - ninja test

# Disable notifications
notifications:
  email: false

# before_deploy:
# # Set up git user name and tag this commit
#   - git config --local user.name "François-David Collin"
#   - git config --local user.email "Francois-David.Collin@umontpellier.fr"
#   - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
#   - git tag $TRAVIS_TAG
# deploy:
#   provider: releases
#   api_key: 
#     secure: "5569e68ec5dbc0c1066b86a80ed3207a81b58195"
#   file: "ModelChoice"
#   skip_cleanup: true
#   on:
#     tags: true