env: 
  - CMAKE_CMD_OPTION="-DENABLE_TESTING=1 -DLAPACK_ROOT=/opt/intel/compilers_and_libraries_2019.1.144/linux/mkl -DLAPACK_LIBRARIES=libmkl_intel_ilp64.a;libmkl_intel_thread.a;libmkl_core.a"

matrix:
  include:
    - os: linux
      sudo: true
      dist: xenial
      compiler: gcc
      addons:
        apt:
          sources: 
            - sourceline: 'ppa:mhier/libboost-latest'
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

    # - os: osx
    #   osx_image: xcode8
    #   env:
    #     - MATRIX_EVAL="brew install clang && CC=clang && CXX=clang++"

addons:
  apt:
    packages:
      - cmake
      - libboost-dev
      - libboost-test-dev
      - libboost-regex


script:
  - mkdir build
  - cd build
  - cmake .. $CMAKE_CMD_OPTION
  - make -j 2
  - make test

before_install:
  - wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
  - sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
  - sudo sh -c 'echo deb https://apt.repos.intel.com/mkl all main > /etc/apt/sources.list.d/intel-mkl.list'
  - sudo apt update
  - sudo apt install intel-mkl-64bit-2019.1-053
  - eval "${MATRIX_EVAL}"

# Hook code coverage report with codecov.io
# after_success:
    # Creating report
  # - cd ${TRAVIS_BUILD_DIR}
  # - lcov --directory . --capture --output-file coverage.info # capture coverage info
  # - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
  # - lcov --list coverage.info #debug info
  # # Uploading report to CodeCov
  # - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

# Disable notifications
notifications:
  email: false