language: cpp
compiler: gcc

matrix:
  include:
    - os: linux
      sudo: true
      dist: bionic
      compiler: gcc
      addons:
        apt:
          sources: 
            # https://software.intel.com/en-us/articles/installing-intel-free-libs-and-python-apt-repo
            - sourceline: 'deb https://apt.repos.intel.com/mkl all main'
              key_url: https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
          packages:
            - clang-8
            - libc++-8-dev
            - libc++abi-8-dev
            - cmake
            - ninja-build
            - intel-mkl-64bit-2019.2-057
      env:
        - MATRIX_EVAL="CC=clang-8 && CXX=clang++-8 CXXFLAGS=\"-static -stdlib=libc++\" MKLROOT=/opt/intel/compilers_and_libraries/linux/mkl"

    # - os: osx
    #   osx_image: xcode8
    #   env:
    #     - MATRIX_EVAL="brew install clang && CC=clang && CXX=clang++"

script:
  - mkdir build
  - cd build
  - cmake -G Ninja 
          -DCMAKE_BUILD_TYPE=Release
          -DRFTEST_TOLERANCE=2e-2
          ..
  - ninja
  - ninja test

# Disable notifications
notifications:
  email: false

before_deploy:
# Set up git user name and tag this commit
  - git config --local user.name "François-David Collin"
  - git config --local user.email "Francois-David.Collin@umontpellier.fr"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key: 
    secure: "PXoNWAKQXJt5kc6LTpf3VAgV10IpP0JiYvJ1b1gD6N2RZXqCuZcgkEnywoIshyuvrSzAqwDA8GI7PmfpzSDS6nq8WvrXIxFzmPNBeEHJX7h0CHc1O1wm7CJusj5JfvHKRokD9JohJ6JYojyy1+RridrxFiSgzoUOVTlje2Aidl3oSV0dC9LEic57e+u4hYDeEQeUsoTjj+ly9ZbL7iNVEHbFdq1VwoISddVgE7xZy+dl3wz/67ofEbpRj0v8gXeVj/ayLiy37puM755r8f0AwhWe0ZAbl8TEVAL2jd/MeqbejtyLPvb0FYsDoWTzALfzPKzyEeOT8N4x80d36JNhxB0I7//FlxhpVlZAJo0q3U6Q4D4phznDlcMlWUjfDw2LXqSc1g/Hnxs2LG4xbManKVSC8pUzH5XuV/r7dcF4opVD7g3QPoNTsHnzmYCeIOI/q9qggaC1i1jcztGn2sq42Kh2pD3Mafv5pqh2uXL9tzqHivbPvvo7+EXgse9bDZ+BhKJ2xDWfl7j6GimD5e8/I9HOcydpp+fZZBWyMa8WH3Rz2lHCMab8BzQgnGfqDyyD9l2gtq+1o7jX8kBGyOvp6MYb8eU6OJWjq/Vb8WLNU8NdY/Mw9kUeH/NPynLhgPLdO0+RwqGq4kjO2EogQKTgXdvt68Ia4syepSFkFKMSKnc="
  file: 
    - "ModelChoice"
    - "EstimParam"
  skip_cleanup: true
  on:
    repo: fradav/abcranger
  branches:    
    - master

    
