language: cpp
compiler: gcc

matrix:
  include:
    - os: linux
      sudo: true
      dist: xenial
      compiler: gcc
      addons:
        apt:
          sources: 
            - sourceline: 'ppa:mhier/libboost-latest'
            # https://software.intel.com/en-us/articles/installing-intel-free-libs-and-python-apt-repo
            - sourceline: 'deb https://apt.repos.intel.com/mkl all main'
              key_url: https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - cmake
            - libboost1.68-dev
            - libhdf5-dev
            - intel-mkl-64bit-2019.2-057
            - libgomp1
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

    # - os: osx
    #   osx_image: xcode8
    #   env:
    #     - MATRIX_EVAL="brew install clang && CC=clang && CXX=clang++"

script:
  - mkdir build
  - cd build
  - eval "${MATRIX_EVAL}"
  - cmake -DLAPACK_ROOT=/opt/intel/compilers_and_libraries/linux/mkl/lib/intel64
          -DLAPACK_LIBRARIES="mkl_intel_lp64;mkl_gnu_thread;mkl_core;gomp"
          -DCMAKE_BUILD_TYPE=Release
          -DRFTEST_TOLERANCE=2e-2
          ..
  - make -j 2 VERBOSE=1
  - make test

# Disable notifications
notifications:
  email: false